package com.teacher.productivitylauncher.presentation.widgets

val lifeTipsQuotes = listOf(
    "🌅 Small daily habits build a powerful future.",
    "💰 Save a little today, live peacefully tomorrow.",
    "👨‍👩‍👧 Your children learn more from your actions than your words.",
    "⏰ A disciplined morning creates a successful day.",
    "😴 Sleep early, wake early, think clearly.",
    "💪 Consistency beats motivation.",
    "💎 Every coin saved is a step toward freedom.",
    "🏠 A calm home begins with calm words.",
    "👨‍👩‍👧‍👦 Time spent with family is never wasted.",
    "🍎 Healthy habits create a healthy mind.",
    "📊 Control your expenses before expenses control your life.",
    "🎯 One productive hour is worth more than a busy day.",
    "🔮 Your future depends on what you repeatedly do.",
    "😌 Rest is not laziness; it is preparation.",
    "📚 Teach children values before valuables.",
    "🙏 Peace grows where gratitude lives.",
    "💸 Avoid unnecessary spending; invest in meaningful living.",
    "🧹 A clean routine creates a clean mind.",
    "🦁 Patience in hard times builds strong character.",
    "🏆 Success is hidden inside daily discipline.",
    "📈 Good habits are silent investments.",
    "👨‍👩‍👧 A wise parent builds both savings and memories.",
    "🛡️ Protect your sleep like you protect your money.",
    "😊 Simple living brings deep happiness.",
    "🎁 The best family gift is your attention.",
    "💡 Spend less on showing off, more on growing.",
    "📅 Tiny improvements every day create big results.",
    "🎯 Your habits shape your destiny.",
    "💵 Financial peace begins with self-control.",
    "🧠 A focused mind creates a meaningful life.",
    "👀 Children copy your lifestyle, not your advice.",
    "🔒 Discipline today creates comfort tomorrow.",
    "🌙 A peaceful night starts with a productive day.",
    "📈 Growth begins when excuses end.",
    "💎 Saving money is a form of self-respect.",
    "🏡 Strong families are built with time, care, and patience.",
    "🌃 Late nights steal tomorrow's energy.",
    "📋 Good routines reduce stress.",
    "🔄 The secret of success is daily repetition.",
    "❤️ Protect your health before illness teaches you its value."
)